# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dtr_core', '~> 0.4.0'
gem 'dtr_to_rust', '~> 0.0.4'
gem 'ffi'

group :test do
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
end

ruby '3.2.2'
