# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dtr_core', path: '../dtr_core'
gem 'dtr_to_rust', path: '../dtr_to_rust'
gem 'ffi'

group :test do
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
end

ruby '3.2.2'
