# frozen_string_literal: true

source 'https://rubygems.org'

# Gems here

gem 'dtr_core', '~> 0.4.1'

group :test do
  gem 'pry'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
end

ruby '3.2.2'
